### ISSUE TITLE
Chapter 3 Question

### ISSUE THREAD

**Issue by mohamedallapitchai** [kinabalu/websocketsbook#3]
When I shutdown the server in ch03/notifications the closeSocket() from "process.on" handler called.
Basically what is the value of the "client_uuid" in this case ? Please note that I am stopping the server and not just particular browser client. In my case I am seeing that the client id (client_uuid) is always the first client which is connected to the server.  Why it is the case ? Can you please explain ?

Note: Actually this is not an issue but a question and I thought that using github is the fastest mode to get the response from the author. Please excuse me.

Thanks & Regards,
Mohamed

**Comment by kinabalu** [comment]
Let's say 4 clients are connected to the server.  `client_uuid` will have the id for each of the clients as they receive the disconnection message over WebSocket.  Remember this all gets referenced from within the `wss.on('connection', function(ws) {` call.

Please re-open if you have more questions, thanks!
